import re


_BASE_PATH = "assets/sounds/"


def _path_to(relpath, filename):
    return f"assets/sounds/{relpath}/{filename}"


def camel_to_snake(name):
    name = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    name = re.sub('(.)([a-z])([0-9]+)', r'\1\2_\3', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', name).lower()


class SFX2020:
    _p = "SFX2020"
    access_denied_now                      = _path_to(_p,  "AccessDeniedNow.wav")
    attention_voltage                      = _path_to(_p,  "AttentionVoltage.wav")
    bad_landing_zone                       = _path_to(_p,  "BadLandingZone.wav")
    beat_my_face_nes_style                 = _path_to(_p,  "BeatMyFaceNESStyle.wav")
    bot_changing_direction                 = _path_to(_p, "BotChangingDirection.wav")
    break_through_the_wall                 = _path_to(_p, "BreakThroughTheWall.wav")
    bullet_bounce                          = _path_to(_p, "BulletBounce.wav")
    bullet_drop_on                         = _path_to(_p, "BulletDropOn.wav")
    bullet_slam                            = _path_to(_p, "BulletSlam.wav")
    bullet_snappin                         = _path_to(_p, "BulletSnappin.wav")
    catapult_mini_bomb                     = _path_to(_p, "CatapultMiniBomb.wav")
    catch_me_if_you_can                    = _path_to(_p, "CatchMeIfYouCan.wav")
    changing_direction                     = _path_to(_p, "ChangingDirection.wav")
    check_menu_item_2                      = _path_to(_p, "CheckMenuItem2.wav")
    check_menu_item                        = _path_to(_p, "CheckMenuItem.wav")
    circling_power                         = _path_to(_p, "CirclingPower.wav")
    cloning_scanning_unit                  = _path_to(_p, "CloningScanningUnit.wav")
    command_not_available                  = _path_to(_p, "CommandNotAvailable.wav")
    communication_line_ready               = _path_to(_p, "CommunicationLineReady.wav")
    confused_attack_style                  = _path_to(_p, "ConfusedAttackStyle.wav")
    confusing_energy_exchange              = _path_to(_p, "ConfusingEnergyExchange.wav")
    confusing_falling_down                 = _path_to(_p, "ConfusingFallingDown.wav")
    connection_interrupted                 = _path_to(_p, "ConnectionInterrupted.wav")
    construction_ready                     = _path_to(_p, "ConstructionReady.wav")
    coordinates_received                   = _path_to(_p, "CoordinatesReceived.wav")
    crystal_destroy                        = _path_to(_p, "CrystalDestroy.wav")
    data_computed_2                        = _path_to(_p, "DataComputed2.wav")
    data_computed_3                        = _path_to(_p, "DataComputed3.wav")
    data_computed                          = _path_to(_p, "DataComputed.wav")
    data_stored_and_ready                  = _path_to(_p, "DataStoredAndReady.wav")
    definite_hit_2                         = _path_to(_p, "DefiniteHit2.wav")
    definite_hit                           = _path_to(_p, "DefiniteHit.wav")
    definite_missile_launch                = _path_to(_p, "DefiniteMissileLaunch.wav")
    definite_shot_2                        = _path_to(_p, "DefiniteShot2.wav")
    definite_shot_3                        = _path_to(_p, "DefiniteShot3.wav")
    definite_shot_4                        = _path_to(_p, "DefiniteShot4.wav")
    definite_shot_5                        = _path_to(_p, "DefiniteShot5.wav")
    definite_shot                          = _path_to(_p, "DefiniteShot.wav")
    deploying_detector                     = _path_to(_p, "DeployingDetector.wav")
    deploying_special_field_area           = _path_to(_p, "DeployingSpecialFieldArea.wav")
    deploy_sensors_scanning_area           = _path_to(_p, "DeploySensorsScanningArea.wav")
    destroy_monster_2                      = _path_to(_p, "DestroyMonster2.wav")
    destroy_monster                        = _path_to(_p, "DestroyMonster.wav")
    digital_laugh                          = _path_to(_p, "DigitalLaugh.wav")
    digital_rearrange                      = _path_to(_p, "DigitalRearrange.wav")
    direct_attack                          = _path_to(_p, "DirectAttack.wav")
    direct_fire_blade_damage               = _path_to(_p, "DirectFireBladeDamage.wav")
    direct_laser_attack                    = _path_to(_p, "DirectLaserAttack.wav")
    direct_laser_blade_attack              = _path_to(_p, "DirectLaserBladeAttack.wav")
    distance_is_too_far                    = _path_to(_p, "DistanceIsTooFar.wav")
    dont_understand_your_language          = _path_to(_p, "DontUnderstandYourLanguage.wav")
    double_laser_shot                      = _path_to(_p, "DoubleLaserShot.wav")
    double_mega_laser_shot                 = _path_to(_p, "DoubleMegaLaserShot.wav")
    dramatic_hitpoint                      = _path_to(_p, "DramaticHitpoint.wav")
    dramatic_scene_sound                   = _path_to(_p, "DramaticSceneSound.wav")
    drone_fly                              = _path_to(_p, "DroneFly.wav")
    drop_longer                            = _path_to(_p, "DropLonger.wav")
    drop_mini                              = _path_to(_p, "DropMini.wav")
    elastic_shield_attack_2                = _path_to(_p, "ElasticShieldAttack2.wav")
    elastic_shield_attack                  = _path_to(_p, "ElasticShieldAttack.wav")
    electric_attack_direct                 = _path_to(_p, "ElectricAttackDirect.wav")
    electric_attack                        = _path_to(_p, "ElectricAttack.wav")
    electric_defense                       = _path_to(_p, "ElectricDefense.wav")
    electric_field                         = _path_to(_p, "ElectricField.wav")
    electric_gate_power_on                 = _path_to(_p, "ElectricGatePowerOn.wav")
    electric_impression_2                  = _path_to(_p, "ElectricImpression2.wav")
    electric_impression                    = _path_to(_p, "ElectricImpression.wav")
    electricity_short                      = _path_to(_p, "ElectricityShort.wav")
    electricity                            = _path_to(_p, "Electricity.wav")
    end_of_power_short                     = _path_to(_p, "EndOfPowerShort.wav")
    enemy_flying_monster_special_attack    = _path_to(_p, "EnemyFlyingMonsterSpecialAttack.wav")
    energetic_shield                       = _path_to(_p, "EnergeticShield.wav")
    energeting_circling_upload             = _path_to(_p, "EnergetingCirclingUpload.wav")
    energy_changing                        = _path_to(_p, "EnergyChanging.wav")
    energy_decrease_shot                   = _path_to(_p, "EnergyDecreaseShot.wav")
    energy_level_very_low                  = _path_to(_p, "EnergyLevelVeryLow.wav")
    energy_reloaded_to_maximum             = _path_to(_p, "EnergyReloadedToMaximum.wav")
    energy_shield_activated                = _path_to(_p, "EnergyShieldActivated.wav")
    energy_upload_to_max_level_shorter     = _path_to(_p, "EnergyUploadToMaxLevelShorter.wav")
    energy_upload_to_max_level             = _path_to(_p, "EnergyUploadToMaxLevel.wav")
    extra_hit_point                        = _path_to(_p, "ExtraHitPoint.wav")
    extreme_interruption                   = _path_to(_p, "ExtremeInterruption.wav")
    falling_down_again_2                   = _path_to(_p, "FallingDownAgain2.wav")
    falling_down_again_3                   = _path_to(_p, "FallingDownAgain3.wav")
    falling_down_again                     = _path_to(_p, "FallingDownAgain.wav")
    fallin_star_longer                     = _path_to(_p, "FallinStarLonger.wav")
    fallin_star                            = _path_to(_p, "FallinStar.wav")
    fast_monster_sound                     = _path_to(_p, "FastMonsterSound.wav")
    fast_space_ships_beside_me             = _path_to(_p, "FastSpaceShipsBesideMe.wav")
    final_shield_defense                   = _path_to(_p, "FinalShieldDefense.wav")
    fire_burn_out                          = _path_to(_p, "FireBurnOut.wav")
    flip_attack_style                      = _path_to(_p, "FlipAttackStyle.wav")
    following_coordinates                  = _path_to(_p, "FollowingCoordinates.wav")
    force_resource_gathering               = _path_to(_p, "ForceResourceGathering.wav")
    funky_explosion                        = _path_to(_p, "FunkyExplosion.wav")
    funky_laser_attack                     = _path_to(_p, "FunkyLaserAttack.wav")
    galactic_gate_interruption             = _path_to(_p, "GalacticGateInterruption.wav")
    gather_bots_attack_each_other          = _path_to(_p, "GatherBotsAttackEachOther.wav")
    gather_unit_hurt                       = _path_to(_p, "GatherUnitHurt.wav")
    get_a_power_up                         = _path_to(_p, "GetAPowerUp.wav")
    get_extra_energy_level                 = _path_to(_p, "GetExtraEnergyLevel.wav")
    get_the_space_item                     = _path_to(_p, "GetTheSpaceItem.wav")
    get_up_power_item                      = _path_to(_p, "GetUpPowerItem.wav")
    greater_hit                            = _path_to(_p, "GreaterHit.wav")
    happy_uploading_battery                = _path_to(_p, "HappyUploadingBattery.wav")
    hard_rocket_launch                     = _path_to(_p, "HardRocketLaunch.wav")
    heli_ship_langing                      = _path_to(_p, "HeliShipLanging.wav")
    heli_ship_langing_wrong                = _path_to(_p, "HeliShipLangingWrong.wav")
    hit_on_energetic_shield                = _path_to(_p, "HitOnEnergeticShield.wav")
    hit_on_me                              = _path_to(_p, "HitOnMe.wav")
    hit_the_ground                         = _path_to(_p, "HitTheGround.wav")
    i_get_your_power                       = _path_to(_p, "IGetYourPower.wav")
    immediate_laser_attack                 = _path_to(_p, "ImmediateLaserAttack.wav")
    impact_mini                            = _path_to(_p, "ImpactMini.wav")
    impact_on_steel_shield                 = _path_to(_p, "ImpactOnSteelShield.wav")
    impact_on_steel_smooth                 = _path_to(_p, "ImpactOnSteelSmooth.wav")
    insufficient_energy                    = _path_to(_p, "InsufficientEnergy.wav")
    insufficient_time                      = _path_to(_p, "InsufficientTime.wav")
    interference                           = _path_to(_p, "Interference.wav")
    interruption_method_2                  = _path_to(_p, "InterruptionMethod2.wav")
    interruption_method                    = _path_to(_p, "InterruptionMethod.wav")
    interruption                           = _path_to(_p, "Interruption.wav")
    invalid_target                         = _path_to(_p, "InvalidTarget.wav")
    item_selected                          = _path_to(_p, "ItemSelected.wav")
    jump_on_it                             = _path_to(_p, "JumpOnIt.wav")
    just_a_little_coin                     = _path_to(_p, "JustALittleCoin.wav")
    just_a_swish                           = _path_to(_p, "JustASwish.wav")
    laser_attack_mini                      = _path_to(_p, "LaserAttackMini.wav")
    laser_mini_shot                        = _path_to(_p, "LaserMiniShot.wav")
    laser_monster_attack                   = _path_to(_p, "LaserMonsterAttack.wav")
    laser_shot                             = _path_to(_p, "LaserShot.wav")
    little_bit_of_crystal_reward           = _path_to(_p, "LittleBitOfCrystalReward.wav")
    little_falling_down                    = _path_to(_p, "LittleFallingDown.wav")
    little_reward                          = _path_to(_p, "LittleReward.wav")
    long_energetic_refresh                 = _path_to(_p, "LongEnergeticRefresh.wav")
    low_bass_hit                           = _path_to(_p, "LowBassHit.wav")
    mass_gun_shots                         = _path_to(_p, "MassGunShots.wav")
    mech_is_ready                          = _path_to(_p, "MechIsReady.wav")
    mech_movement_ready                    = _path_to(_p, "MechMovementReady.wav")
    mega_missile_launch                    = _path_to(_p, "MegaMissileLaunch.wav")
    mega_upload_power_up                   = _path_to(_p, "MegaUploadPowerUp.wav")
    mine_detected_2                        = _path_to(_p, "MineDetected2.wav")
    mine_detected                          = _path_to(_p, "MineDetected.wav")
    mini_blade_direct_attack               = _path_to(_p, "MiniBladeDirectAttack.wav")
    mini_bot_system_fast_restart           = _path_to(_p, "MiniBotSystemFastRestart.wav")
    mini_bot_systems_ready                 = _path_to(_p, "MiniBotSystemsReady.wav")
    mini_explosion_chain_reaction          = _path_to(_p, "MiniExplosionChainReaction.wav")
    mini_hit_impact_2                      = _path_to(_p, "MiniHitImpact2.wav")
    mini_hit_impact                        = _path_to(_p, "MiniHitImpact.wav")
    mini_hit_nice                          = _path_to(_p, "MiniHitNice.wav")
    mini_hit_point                         = _path_to(_p, "MiniHitPoint.wav")
    mini_hit                               = _path_to(_p, "MiniHit.wav")
    mini_laser_attack_2                    = _path_to(_p, "MiniLaserAttack2.wav")
    mini_laser_attack_3                    = _path_to(_p, "MiniLaserAttack3.wav")
    mini_laser_attack_4                    = _path_to(_p, "MiniLaserAttack4.wav")
    mini_laser_attack                      = _path_to(_p, "MiniLaserAttack.wav")
    minimal_space_warp                     = _path_to(_p, "MinimalSpaceWarp.wav")
    mini_monster_destroy                   = _path_to(_p, "MiniMonsterDestroy.wav")
    mini_rocket_flies_beside_me            = _path_to(_p, "MiniRocketFliesBesideMe.wav")
    mini_shield_attack_2                   = _path_to(_p, "MiniShieldAttack2.wav")
    mini_shield_attack                     = _path_to(_p, "MiniShieldAttack.wav")
    mini_shot_2                            = _path_to(_p, "MiniShot2.wav")
    mini_shot_3                            = _path_to(_p, "MiniShot3.wav")
    mini_shot_4                            = _path_to(_p, "MiniShot4.wav")
    mini_shot                              = _path_to(_p, "MiniShot.wav")
    mini_space_blade_attack                = _path_to(_p, "MiniSpaceBladeAttack.wav")
    missile_beside_me                      = _path_to(_p, "MissileBesideMe.wav")
    missile_burn_out                       = _path_to(_p, "MissileBurnOut.wav")
    missile_fire                           = _path_to(_p, "MissileFire.wav")
    missile_launch_fast                    = _path_to(_p, "MissileLaunchFast.wav")
    missile_launch_mini_2                  = _path_to(_p, "MissileLaunchMini2.wav")
    missile_launch_mini                    = _path_to(_p, "MissileLaunchMini.wav")
    missile_launch                         = _path_to(_p, "MissileLaunch.wav")
    missile_mini                           = _path_to(_p, "MissileMini.wav")
    monster_changing_direction             = _path_to(_p, "MonsterChangingDirection.wav")
    monster_downground_effect              = _path_to(_p, "MonsterDowngroundEffect.wav")
    monster_energy_reload_full             = _path_to(_p, "MonsterEnergyReloadFull.wav")
    monster_energy_reload                  = _path_to(_p, "MonsterEnergyReload.wav")
    monster_goes_wrong_way                 = _path_to(_p, "MonsterGoesWrongWay.wav")
    monster_hit_mini                       = _path_to(_p, "MonsterHitMini.wav")
    monster_movement                       = _path_to(_p, "MonsterMovement.wav")
    monster_runaway                        = _path_to(_p, "MonsterRunaway.wav")
    monster_selected                       = _path_to(_p, "MonsterSelected.wav")
    monster_spike_attack                   = _path_to(_p, "MonsterSpikeAttack.wav")
    monster_unburrow                       = _path_to(_p, "MonsterUnburrow.wav")
    monster_upground_effect                = _path_to(_p, "MonsterUpgroundEffect.wav")
    multiple_interruption_signals          = _path_to(_p, "MultipleInterruptionSignals.wav")
    multiple_laser_attack                  = _path_to(_p, "MultipleLaserAttack.wav")
    multi_power_up_grade                   = _path_to(_p, "MultiPowerUpGrade.wav")
    multi_upload                           = _path_to(_p, "MultiUpload.wav")
    my_shield_is_stronger                  = _path_to(_p, "MyShieldIsStronger.wav")
    new_ability_or_upgrade_available       = _path_to(_p, "NewAbilityOrUpgradeAvailable.wav")
    new_hit_point                          = _path_to(_p, "NewHitPoint.wav")
    no_more_power_robot                    = _path_to(_p, "NoMorePowerRobot.wav")
    not_enough_energy                      = _path_to(_p, "NotEnoughEnergy.wav")
    observer_detect_an_important_resource  = _path_to(_p, "ObserverDetectAnImportantResource.wav")
    observer_falling_down                  = _path_to(_p, "ObserverFallingDown.wav")
    observer_found_new_area                = _path_to(_p, "ObserverFoundNewArea.wav")
    observer_new_upgrade_ready             = _path_to(_p, "ObserverNewUpgradeReady.wav")
    observer_power_off_and_dead            = _path_to(_p, "ObserverPowerOffAndDead.wav")
    observer_reporting                     = _path_to(_p, "ObserverReporting.wav")
    observer_runaway_from_enemy            = _path_to(_p, "ObserverRunawayFromEnemy.wav")
    observer_runaway                       = _path_to(_p, "ObserverRunaway.wav")
    observer_select_movement               = _path_to(_p, "ObserverSelectMovement.wav")
    option_select                          = _path_to(_p, "OptionSelect.wav")
    path_finding_bot_wrong_way             = _path_to(_p, "PathFindingBotWrongWay.wav")
    perfect_shield_guard                   = _path_to(_p, "PerfectShieldGuard.wav")
    point_selected                         = _path_to(_p, "PointSelected.wav")
    power_off_short                        = _path_to(_p, "PowerOffShort.wav")
    radio_connection_on                    = _path_to(_p, "RadioConnectionOn.wav")
    recall_teleport_action                 = _path_to(_p, "RecallTeleportAction.wav")
    reloading_machine_is_empty             = _path_to(_p, "ReloadingMachineIsEmpty.wav")
    reload_on_battery                      = _path_to(_p, "ReloadOnBattery.wav")
    reload_rocket_launchers                = _path_to(_p, "ReloadRocketLaunchers.wav")
    robot_found_an_obstacle                = _path_to(_p, "RobotFoundAnObstacle.wav")
    robot_loses_energy                     = _path_to(_p, "RobotLosesEnergy.wav")
    robot_malfunction                      = _path_to(_p, "RobotMalfunction.wav")
    robot_options_select                   = _path_to(_p, "RobotOptionsSelect.wav")
    robot_slide_on_direction_change        = _path_to(_p, "RobotSlideOnDirectionChange.wav")
    rocket_beside_me                       = _path_to(_p, "RocketBesideMe.wav")
    rocket_burn                            = _path_to(_p, "RocketBurn.wav")
    rocket_launch_mini                     = _path_to(_p, "RocketLaunchMini.wav")
    rocket_mini                            = _path_to(_p, "RocketMini.wav")
    rocket_shot                            = _path_to(_p, "RocketShot.wav")
    rocket_smoke                           = _path_to(_p, "RocketSmoke.wav")
    secret_mine_planted                    = _path_to(_p, "SecretMinePlanted.wav")
    select_an_option_2                     = _path_to(_p, "SelectAnOption2.wav")
    select_an_option                       = _path_to(_p, "SelectAnOption.wav")
    select_a_point                         = _path_to(_p, "SelectAPoint.wav")
    select_menu_item_or_hover              = _path_to(_p, "SelectMenuItemOrHover.wav")
    sending_message_outa_space             = _path_to(_p, "SendingMessageOutaSpace.wav")
    sharp_blade_attack                     = _path_to(_p, "SharpBladeAttack.wav")
    shield_defends_bullets                 = _path_to(_p, "ShieldDefendsBullets.wav")
    shield_detected                        = _path_to(_p, "ShieldDetected.wav")
    shield_mini_defend                     = _path_to(_p, "ShieldMiniDefend.wav")
    short_circuit_robot                    = _path_to(_p, "ShortCircuitRobot.wav")
    short_select_button                    = _path_to(_p, "ShortSelectButton.wav")
    short_signal_sound                     = _path_to(_p, "ShortSignalSound.wav")
    shot_me_down                           = _path_to(_p, "ShotMeDown.wav")
    shot_on_a_monster                      = _path_to(_p, "ShotOnAMonster.wav")
    sight_range_increased                  = _path_to(_p, "SightRangeIncreased.wav")
    simple_missile_launch                  = _path_to(_p, "SimpleMissileLaunch.wav")
    simply_target_point                    = _path_to(_p, "SimplyTargetPoint.wav")
    single_shot_2                          = _path_to(_p, "SingleShot2.wav")
    single_shot_3                          = _path_to(_p, "SingleShot3.wav")
    single_shot_4                          = _path_to(_p, "SingleShot4.wav")
    single_shot                            = _path_to(_p, "SingleShot.wav")
    smooth_attack_style                    = _path_to(_p, "SmoothAttackStyle.wav")
    smooth_laser_attack                    = _path_to(_p, "SmoothLaserAttack.wav")
    smooth_weapon_attack                   = _path_to(_p, "SmoothWeaponAttack.wav")
    some_little_spike_hurt_2               = _path_to(_p, "SomeLittleSpikeHurt2.wav")
    some_little_spike_hurt                 = _path_to(_p, "SomeLittleSpikeHurt.wav")
    some_missile_impacted                  = _path_to(_p, "SomeMissileImpacted.wav")
    space_coin_dropped                     = _path_to(_p, "SpaceCoinDropped.wav")
    space_destroy_mini_ship                = _path_to(_p, "SpaceDestroyMiniShip.wav")
    space_gun_fire_2                       = _path_to(_p, "SpaceGunFire2.wav")
    space_gun_fire                         = _path_to(_p, "SpaceGunFire.wav")
    space_gun_reload                       = _path_to(_p, "SpaceGunReload.wav")
    space_heli_arrived                     = _path_to(_p, "SpaceHeliArrived.wav")
    space_obstacle_2                       = _path_to(_p, "SpaceObstacle2.wav")
    space_obstacle                         = _path_to(_p, "SpaceObstacle.wav")
    space_police_is_coming                 = _path_to(_p, "SpacePoliceIsComing.wav")
    space_ship_electric_interference       = _path_to(_p, "SpaceShipElectricInterference.wav")
    space_ship_interruption                = _path_to(_p, "SpaceShipInterruption.wav")
    special_bomb_has_been_planted          = _path_to(_p, "SpecialBombHasBeenPlanted.wav")
    special_mini_reward                    = _path_to(_p, "SpecialMiniReward.wav")
    special_nearly_attack_style            = _path_to(_p, "SpecialNearlyAttackStyle.wav")
    special_reward_reloaded                = _path_to(_p, "SpecialRewardReloaded.wav")
    special_reward_short_2                 = _path_to(_p, "SpecialRewardShort2.wav")
    special_reward_short                   = _path_to(_p, "SpecialRewardShort.wav")
    special_reward                         = _path_to(_p, "SpecialReward.wav")
    special_weapon                         = _path_to(_p, "SpecialWeapon.wav")
    stones_slam_to_the_ground              = _path_to(_p, "StonesSlamToTheGround.wav")
    strange_signal_detected                = _path_to(_p, "StrangeSignalDetected.wav")
    suddenly_falling_down                  = _path_to(_p, "SuddenlyFallingDown.wav")
    suprise_reward_short                   = _path_to(_p, "SupriseRewardShort.wav")
    suprise_reward                         = _path_to(_p, "SupriseReward.wav")
    time_is_out_soon                       = _path_to(_p, "TimeIsOutSoon.wav")
    total_burn_out                         = _path_to(_p, "TotalBurnOut.wav")
    ufo_destroyed_falling_down             = _path_to(_p, "UFODestroyedFallingDown.wav")
    ufo_destroyed                          = _path_to(_p, "UFODestroyed.wav")
    ufo_fly_above_me                       = _path_to(_p, "UFOFlyAboveMe.wav")
    unable_landing_area                    = _path_to(_p, "UnableLandingArea.wav")
    unable_to_gather_resource              = _path_to(_p, "UnableToGatherResource.wav")
    unclear_instructions                   = _path_to(_p, "UnclearInstructions.wav")
    unit_cant_move_on                      = _path_to(_p, "UnitCantMoveOn.wav")
    unit_flip_2                            = _path_to(_p, "UnitFlip2.wav")
    unit_flip                              = _path_to(_p, "UnitFlip.wav")
    unit_loses_energetic_shield            = _path_to(_p, "UnitLosesEnergeticShield.wav")
    units_detect_in_area                   = _path_to(_p, "UnitsDetectInArea.wav")
    unit_selected_with_very_low_power      = _path_to(_p, "UnitSelectedWithVeryLowPower.wav")
    unknown_attak_style                    = _path_to(_p, "UnknownAttakStyle.wav")
    unknown_objects_in_area                = _path_to(_p, "UnknownObjectsInArea.wav")
    unknown_power                          = _path_to(_p, "UnknownPower.wav")
    unknown_shot_style                     = _path_to(_p, "UnknownShotStyle.wav")
    unknown_signal_2                       = _path_to(_p, "UnknownSignal2.wav")
    unknown_signal                         = _path_to(_p, "UnknownSignal.wav")
    unkown_resource_or_enemy_detected      = _path_to(_p, "UnkownResourceOrEnemyDetected.wav")
    unsure_direction_bot_2                 = _path_to(_p, "UnsureDirectionBot2.wav")
    unsure_direction_bot                   = _path_to(_p, "UnsureDirectionBot.wav")
    unsure_select                          = _path_to(_p, "UnsureSelect.wav")
    unusual_coin_reward                    = _path_to(_p, "UnusualCoinReward.wav")
    unusual_reward_sound                   = _path_to(_p, "UnusualRewardSound.wav")
    unusual_shield_detection               = _path_to(_p, "UnusualShieldDetection.wav")
    upload_gun_before_energetic_explosion  = _path_to(_p, "UploadGunBeforeEnergeticExplosion.wav")
    uploading_ready_bot                    = _path_to(_p, "UploadingReadyBot.wav")
    very_massive_energetic_shield_on       = _path_to(_p, "VeryMassiveEnergeticShieldOn.wav")
    very_short_impact                      = _path_to(_p, "VeryShortImpact.wav")
    very_special_item_discovered_2         = _path_to(_p, "VerySpecialItemDiscovered2.wav")
    very_special_item_discovered           = _path_to(_p, "VerySpecialItemDiscovered.wav")
    weapon_launch_mini                     = _path_to(_p, "WeaponLaunchMini.wav")
    wrong_langing_zone                     = _path_to(_p, "WrongLangingZone.wav")
    wrong_way_bot                          = _path_to(_p, "WrongWayBot.wav")


    @staticmethod
    def _assets_to_code():
        """Utility method that gen's the above boilerplate code (not used at runtime).
        """
        file_to_process = "/home/david/Coding/python/circuits/assets/sounds/SFX2020/0_manifest.txt"

        with open(file_to_process) as f:
            lines = f.readlines()
            lines = [line.rstrip() for line in lines]

        tabs = 10

        for l in lines:
            refname = camel_to_snake(l.replace(".wav", ""))
            if len(refname) < tabs * 4 - 2:
                refname += (" " * ((tabs * 4 - 2) - len(refname)))
            print(f"{refname} = _path_to(\"{l}\")")


class ModernUI:

    _p = "Cyberleaf-ModernUISFX/Sounds"

    camera_snapshot                = _path_to(_p, "CameraSnapshot.wav")
    click_and_slide                = _path_to(_p, "ClickAndSlide.wav")
    clicky_button_1a               = _path_to(_p, "ClickyButton1a.wav")
    clicky_button_1b               = _path_to(_p, "ClickyButton1b.wav")
    clicky_button_2                = _path_to(_p, "ClickyButton2.wav")
    clicky_button_3a               = _path_to(_p, "ClickyButton3a.wav")
    clicky_button_3b               = _path_to(_p, "ClickyButton3b.wav")
    clicky_button_4                = _path_to(_p, "ClickyButton4.wav")
    clicky_button_5a               = _path_to(_p, "ClickyButton5a.wav")
    clicky_button_5b               = _path_to(_p, "ClickyButton5b.wav")
    clicky_button_6                = _path_to(_p, "ClickyButton6.wav")
    clicky_button_7                = _path_to(_p, "ClickyButton7.wav")
    clicky_button_8                = _path_to(_p, "ClickyButton8.wav")
    clicky_button_9a               = _path_to(_p, "ClickyButton9a.wav")
    clicky_button_9b               = _path_to(_p, "ClickyButton9b.wav")
    clicky_button_10a              = _path_to(_p, "ClickyButton10a.wav")
    clicky_button_10b              = _path_to(_p, "ClickyButton10b.wav")
    close_or_disable_1             = _path_to(_p, "CloseOrDisable1.wav")
    close_or_disable_2             = _path_to(_p, "CloseOrDisable2.wav")
    close_or_disable_3             = _path_to(_p, "CloseOrDisable3.wav")
    close_or_disable_4             = _path_to(_p, "CloseOrDisable4.wav")
    close_or_disable_5             = _path_to(_p, "CloseOrDisable5.wav")
    error_1                        = _path_to(_p, "Error1.wav")
    error_2                        = _path_to(_p, "Error2.wav")
    error_3                        = _path_to(_p, "Error3.wav")
    error_4                        = _path_to(_p, "Error4.wav")
    error_5                        = _path_to(_p, "Error5.wav")
    generic_button_1               = _path_to(_p, "GenericButton1.wav")
    generic_button_2               = _path_to(_p, "GenericButton2.wav")
    generic_button_3               = _path_to(_p, "GenericButton3.wav")
    generic_button_4               = _path_to(_p, "GenericButton4.wav")
    generic_button_5               = _path_to(_p, "GenericButton5.wav")
    generic_button_6               = _path_to(_p, "GenericButton6.wav")
    generic_button_7               = _path_to(_p, "GenericButton7.wav")
    generic_button_8               = _path_to(_p, "GenericButton8.wav")
    generic_button_9               = _path_to(_p, "GenericButton9.wav")
    generic_button_10              = _path_to(_p, "GenericButton10.wav")
    generic_button_11              = _path_to(_p, "GenericButton11.wav")
    generic_button_12              = _path_to(_p, "GenericButton12.wav")
    generic_button_13              = _path_to(_p, "GenericButton13.wav")
    generic_button_14              = _path_to(_p, "GenericButton14.wav")
    generic_button_15              = _path_to(_p, "GenericButton15.wav")
    generic_notification_1         = _path_to(_p, "GenericNotification1.wav")
    generic_notification_2         = _path_to(_p, "GenericNotification2.wav")
    generic_notification_3         = _path_to(_p, "GenericNotification3.wav")
    generic_notification_4         = _path_to(_p, "GenericNotification4.wav")
    generic_notification_5         = _path_to(_p, "GenericNotification5.wav")
    generic_notification_6         = _path_to(_p, "GenericNotification6.wav")
    generic_notification_7         = _path_to(_p, "GenericNotification7.wav")
    generic_notification_8         = _path_to(_p, "GenericNotification8.wav")
    generic_notification_9         = _path_to(_p, "GenericNotification9.wav")
    generic_notification_10a       = _path_to(_p, "GenericNotification10a.wav")
    generic_notification_10b       = _path_to(_p, "GenericNotification10b.wav")
    generic_notification_11        = _path_to(_p, "GenericNotification11.wav")
    handle_drag_tick               = _path_to(_p, "HandleDragTick.wav")
    little_noise                   = _path_to(_p, "LittleNoise.wav")
    little_swoosh_1a               = _path_to(_p, "LittleSwoosh1a.wav")
    little_swoosh_1b               = _path_to(_p, "LittleSwoosh1b.wav")
    little_swoosh_2a               = _path_to(_p, "LittleSwoosh2a.wav")
    little_swoosh_2b               = _path_to(_p, "LittleSwoosh2b.wav")
    little_swoosh_3                = _path_to(_p, "LittleSwoosh3.wav")
    little_swoosh_4                = _path_to(_p, "LittleSwoosh4.wav")
    little_swoosh_5                = _path_to(_p, "LittleSwoosh5.wav")
    maximize_1                     = _path_to(_p, "Maximize1.wav")
    maximize_2                     = _path_to(_p, "Maximize2.wav")
    maximize_3                     = _path_to(_p, "Maximize3.wav")
    maximize_4                     = _path_to(_p, "Maximize4.wav")
    minimize_1                     = _path_to(_p, "Minimize1.wav")
    minimize_2                     = _path_to(_p, "Minimize2.wav")
    minimize_3                     = _path_to(_p, "Minimize3.wav")
    minimize_4                     = _path_to(_p, "Minimize4.wav")
    open_or_enable_1               = _path_to(_p, "OpenOrEnable1.wav")
    open_or_enable_2               = _path_to(_p, "OpenOrEnable2.wav")
    open_or_enable_3               = _path_to(_p, "OpenOrEnable3.wav")
    open_or_enable_4a              = _path_to(_p, "OpenOrEnable4a.wav")
    open_or_enable_4b              = _path_to(_p, "OpenOrEnable4b.wav")
    open_or_enable_5               = _path_to(_p, "OpenOrEnable5.wav")
    popup_1                        = _path_to(_p, "Popup1.wav")
    popup_2                        = _path_to(_p, "Popup2.wav")
    popup_3                        = _path_to(_p, "Popup3.wav")
    popup_4a                       = _path_to(_p, "Popup4a.wav")
    popup_4b                       = _path_to(_p, "Popup4b.wav")
    sci_fi_notification_1          = _path_to(_p, "SciFiNotification1.wav")
    sci_fi_notification_2          = _path_to(_p, "SciFiNotification2.wav")
    sci_fi_notification_3          = _path_to(_p, "SciFiNotification3.wav")
    snappy_button_1                = _path_to(_p, "SnappyButton1.wav")
    snappy_button_2                = _path_to(_p, "SnappyButton2.wav")
    snappy_button_3                = _path_to(_p, "SnappyButton3.wav")
    snappy_button_4                = _path_to(_p, "SnappyButton4.wav")
    snappy_button_5                = _path_to(_p, "SnappyButton5.wav")
    success_1                      = _path_to(_p, "Success1.wav")
    success_2                      = _path_to(_p, "Success2.wav")
    success_3                      = _path_to(_p, "Success3.wav")
    success_4                      = _path_to(_p, "Success4.wav")
    success_5                      = _path_to(_p, "Success5.wav")
    success_6                      = _path_to(_p, "Success6.wav")
    success_7a                     = _path_to(_p, "Success7a.wav")
    success_7b                     = _path_to(_p, "Success7b.wav")
    success_9                      = _path_to(_p, "Success9.wav")
    success_10                     = _path_to(_p, "Success10.wav")
    success_11                     = _path_to(_p, "Success11.wav")
    success_12a                    = _path_to(_p, "Success12a.wav")
    success_12b                    = _path_to(_p, "Success12b.wav")
    success_13                     = _path_to(_p, "Success13.wav")
    swoosh_slide_1a                = _path_to(_p, "SwooshSlide1a.wav")
    swoosh_slide_1b                = _path_to(_p, "SwooshSlide1b.wav")
    swoosh_slide_2                 = _path_to(_p, "SwooshSlide2.wav")
    swoosh_slide_3                 = _path_to(_p, "SwooshSlide3.wav")
    swoosh_slide_4                 = _path_to(_p, "SwooshSlide4.wav")
    swoosh_slide_5                 = _path_to(_p, "SwooshSlide5.wav")

    @staticmethod
    def _assets_to_code():
        """Utility method that gen's the above boilerplate code (not used at runtime).
        """

        file_to_process = "/home/david/Coding/python/circuits/assets/sounds/Cyberleaf-ModernUISFX/manifest.txt"

        with open(file_to_process) as f:
            lines = f.readlines()
            lines = [line.rstrip() for line in lines]

        tabs = 8

        for l in lines:
            refname = camel_to_snake(l.replace(".wav", ""))
            if len(refname) < tabs * 4 - 2:
                refname += (" " * ((tabs * 4 - 2) - len(refname)))
            print(f"{refname} = _path_to(_p, \"{l}\")")


MENU_BLIP_1 = ModernUI.clicky_button_3a
MENU_ACCEPT = ModernUI.clicky_button_3b
MENU_ERROR = ModernUI.error_5
MENU_BACK = ModernUI.clicky_button_9b
MENU_EXIT = ModernUI.close_or_disable_5
MENU_START = ModernUI.open_or_enable_4a


if __name__ == "__main__":
    ModernUI._assets_to_code()
